version: "3"
services:
  frontend:
    image: ts-frontend-container
    stdin_open: true
    networks: 
      - mern-app
    ports: 
      - "3000:3000"

  backend:
    image: ts-backend-container
    networks:
      - mern-app
    ports: 
      - "9000:9000"
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
  mongo_seed:
    image: ts-mongo-seed-container
    links:
      - mongo
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local